[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt",
    "app/**",
    "railway.toml",
    "Dockerfile",
]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:${PORT:-5000}"
